# Generated by Django 3.0.4 on 2020-03-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок вакансий'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.CharField(max_length=250, verbose_name='Адрес вакансии'),
        ),
    ]
